defaults:
  - _self_
  - dataset: 300W
  - optimizer: adam
  - model: resnet
  - criterion: mse
  - lr_scheduler: step

batch_size: 64
num_classes: 136
num_epochs: 50
trainset:
  path: data/ibug_300W_large_face_landmark_dataset/labels_ibug_300W_train.xml
testset:
  path: data/ibug_300W_large_face_landmark_dataset/labels_ibug_300W_test.xml
input_size: 224
num_workers: 4
train_type: scratch
lr_threshold: 0.00001
early_stop_patience: 5 